global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # Prometheus self-scrape (nice to have)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape your Spring Boot app inside the compose network
  - job_name: 'spring-boot'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['command-sdk-app:8081']